### ISSUE TITLE
Is there TurfWars

### ISSUE THREAD

**Issue by BlueWhaleYT** [laith98/GamesUI#1]
Hi there,
I knew this is only a UI for selecting the games.As I checked your repositories,I saw that you made some minigames such as SkyWars.I saw that the UI config a option to select TurfWars.Can you make TurfWars plugin for free?
Thanks.
Although  I know this is a request.

**Comment by Laith98Dev** [comment]
I have TurfWars in my server!

**Comment by BlueWhaleYT** [comment]
yes so I want to request make it public.
Thanks.
